# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee2fd5842b2fd56d32d5727df7f3b14d"
name = "auto-reviews-app"
handle = "auto-reviews-app"
application_url = "https://autoreviewsapp.ngrok.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-63bd8013.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://autoreviewsapp.ngrok.app/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
